### PR TITLE
Throw exception if response is empty by invoke method callSync

### PR DESCRIPTION
**Pull request by osbominix**
related issue: 
[Getting empty responses from a localCall.callSync #165](https://github.com/SUSE/salt-netapi-client/issues/165)

### CODE REVIEW

**Comment by lucidd** [comment]
whats the advantage of throwing an exception here? Having an empty result for a minion can mean multiple things. There is no minion that matches, the minion is down, the minion is unreachable, the call took to long and timed out. The salt api does not give us any information about what happened so we can not construct a single error message that fits all.

**Comment by osbominix** [comment]
It is just because the usability. If a call has been invoked, there should be something in the response result. An empty result means multiple things, but it also means nothing. As a user who invokes the call and gets a empty result, it would be helpful for him to show some hints(as exception or log or something else) anywhere, like "Empty result, please check if there is no minion that matches, the minion is down, the minion is unreachable, or the call took to long and timed out. " It seems all callSync methods need a extension to handle this issue.  whatever, I am a newbie in this area of saltstack, maybe an empty result is not that bad in this case, if user doesn't care what is happened behind.

**Comment by lucidd** [comment]
I think this handles a very narrow case. The only time this exception would be thrown is if the result is completely empty. In all other cases where only certain minions have no result but others have it would not be thrown. Errors happen on a minion by minion basis so they have to be checked and handled that way. In addition having a result does not mean you have no error you still need to check the result itself.
I agree that its a bit unintuitive for a user and it would probably be nice if we add some documentation about what a missing result means in terms of salt.

**Comment by osbominix** [comment]
good, so the exception handling has been reverted. 

For the example file Calls.java which may return empty value, a comment has been added there.

**Comment by renner** [comment]
Thanks for your efforts @osbominix, I merged your hint by squashing all your commits!

**Pull request merged**
