### PR TITLE
Better error handling in Runner and Wheel calls

### PR DESCRIPTION
**Pull request by admd**
In case of exception where parser is unable to translate response into a proper type, show the original response from Salt.

Related issues #190

### CODE REVIEW

**Comment by admd** [comment]
@lucidd  I might be missing something but would it make sense if return type of function e.g callSync in RunnelCall be like the Result<R> instead of R,  just like we have in LocalCall so we can get the advantage of 
Xor type.  I know Result<> is meant for minion result but can't we use it for Runner Calls as well.

**Comment by lucidd** [comment]
@admd i think that makes total sense to have the same error handling in Runner and Wheel. I'm not sure tho to what extend the same error handling will work.

**Comment by admd** [comment]
Thank you for your quick response.

**Comment by admd** [comment]
Hi @lucidd , for synchronous methods, I have already made required changes for better error handling. But as asynchronous methods both in Wheel and Runner calls return scheduled job information immidately that we can later use to query the result, I can't think of much advantage here to return this result  wrapped in Result class.  

If you think  it is enough, can you please review my changes and if something is missing, please do let know.

**Comment by admd** [comment]
Thank you.👍

**Comment by mateiw** [comment]
Tested this and seems to work fine. 👍  from me too.

**Pull request merged**
